project:
  type: website
  output-dir: docs #to display as website in github

website:
  title: "Hector Fajardo"
  site-url: https://hectorfajardo.github.io/
  navbar:
    left: 
      - text: Blog
        href: t02_blog.qmd
      - text: Research
        href: t03_research_projects.qmd
      - text: Sci-Comm
        href: t04_scicomm.qmd
      - text: Teaching
        href: t05_teaching.qmd
  page-footer: 
   left: >-
     &#169; 2025 Hector Fajardo &#8729; Made with [Quarto](https://quarto.org)

format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

