project:
  type: website
  output-dir: docs #to display as website in github

website:
  title: "Hector's Blog"
  navbar:
    left: 
      - text: Research
        href: research_projects.qmd
      - text: Sci-Comm
        href: science_communication.qmd
      - text: Resume
        href: resume.qmd
      - text: CV
        href: cv.qmd
    right:
      - text: about
        href: about.qmd

format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

